### ISSUE TITLE
Delete Log File button leaves entry in list

### ISSUE THREAD

**Issue by quozl** [sugarlabs/log-activity#12]
When the delete log file button is used, the file is deleted, but the entry in the Log Files list may remain until the activity is stopped.

**Comment by chimosky** [comment]
@quozl it seems it happens for log files that no longer exist, say logs of activities that existed some minutes ago and are wiped when a new sugar session is started. For other logs, they're deleted from my computer and from the Log Files list.

**Comment by quozl** [comment]
Oh, I see what you're saying now.  The problem occurs for you in the historic directories, not the main logs directory.  Yes, that's what I reproduce now, on Ubuntu 16.04.  I'll edit my original post accordingly.
