### ISSUE TITLE
[Feature Suggestion] Delete key to remove selected log file

### ISSUE THREAD

**Issue by Hrishi1999** [sugarlabs/log-activity#17]
For cleaning up the log files quickly, I added a shortcut method, that is, on pressing the delete key the selected log file would get deleted. I've attached the GIF to see how it works. Does this feature make sense? 
![delete-key](https://user-images.githubusercontent.com/16208722/62008983-2d417580-b177-11e9-8065-5ed42ad6c2ae.gif)

**Comment by walterbender** [comment]
Seems useful.

**Comment by quozl** [comment]
@Hrishi1999, any reason to keep this issue open?  I note there was no "Fixes #N" in the pull request comments.
