### ISSUE TITLE
Gtk-CRITICAL Warning

### ISSUE THREAD

**Issue by Saumya-Mishra9129** [sugarlabs/log-activity#21]
Tested with Ubuntu 20.04 
Open Log activity -> check in .log file of activity-
(sugar-activity3:1855): Gtk-CRITICAL **: 15:34:20.547: gtk_widget_draw: assertion '!widget->priv->alloc_needed' failed

**Comment by quozl** [comment]
Does not reproduce any longer, presumably a GTK update was applied.
